sender:
rabbitmq:
  addr: "amqp://guest:guest@localhost:5672/"
  exchange: calendar
  exchange_type: direct
  queue: notifications
  consumer_tag: calendar-consumer
  binding_key: calendar-key
  reliable: true
  persistent: true