version: "3.9"

services:
  postgres:
    container_name: calendardb
    image: postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "calendarDB"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - default

  rabbitmq:
    container_name: rabbitmq
    # There is a prebuilt RabbitMQ image; see
    # https://hub.docker.com/_/rabbitmq/ for details.
    # This variant is built on Alpine Linux (it's smaller) and includes
    # the management UI.
    image: rabbitmq:3.6-management-alpine
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - default

  calendar:
    container_name: calendar
    build:
      context: .
      dockerfile: build/calendar/Dockerfile
    ports:
      - '8080:8080'
      - '50051:50051'
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - default

  scheduler:
    container_name: scheduler
    build:
      context: .
      dockerfile: build/calendar_scheduler/Dockerfile
    depends_on:
      - rabbitmq
      - calendar
    networks:
      - default

  sender:
    container_name: sender
    build:
      context: .
      dockerfile: build/calendar_sender/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - default

  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: build/migrations/Dockerfile
    environment:
      WAIT_HOSTS: ${POSTGRES_HOST}:${POSTGRES_PORT}
      GOOSE_DRIVER: 'postgres'
      GOOSE_DBSTRING: "user=postgres password=passpass host=localhost dbname=calendarDB sslmode=disable"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - default

  integration:
    container_name: integration_tests
    build:
      context: .
      dockerfile: integration_test/Dockerfile
    depends_on:
      - calendar
    networks:
      - default

networks:
  default:
    driver: bridge
